skl_trade = 0                 ###交易
skl_leadership = 1            ###统领
skl_prisoner_management = 2   ###俘虏
skl_reserved_1 = 3
skl_reserved_2 = 4
skl_reserved_3 = 5
skl_reserved_4 = 6
skl_persuasion = 7            ###说服
skl_engineer = 8              ###工程
skl_first_aid = 9             ###急救
skl_surgery = 10              ###手术
skl_wound_treatment = 11      ###疗伤
skl_inventory_management = 12 ###物品管理
skl_spotting = 13             ###侦察
skl_pathfinding = 14          ###向导
skl_tactics = 15              ###战术
skl_tracking = 16             ###跟踪
skl_trainer = 17              ###教练
skl_reserved_5 = 18
skl_reserved_6 = 19
skl_reserved_7 = 20
skl_reserved_8 = 21
skl_looting = 22              ###掠夺
skl_horse_archery = 23        ###骑射
skl_riding = 24               ###骑术
skl_athletics = 25            ###跑动
skl_shield = 26               ###盾防
skl_weapon_master = 27        ###武器掌握
skl_reserved_9 = 28   
skl_reserved_10 = 29
skl_reserved_11 = 30
skl_reserved_12 = 31
skl_reserved_13 = 32
skl_power_draw = 33           ###强弓
skl_power_throw = 34          ###强掷
skl_power_strike = 35         ###强击
skl_ironflesh = 36            ###铁骨
skl_reserved_14 = 37
skl_reserved_15 = 38
skl_reserved_16 = 39
skl_reserved_17 = 40
skl_reserved_18 = 41


